enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven(url = "https://jitpack.io")
        gradlePluginPortal()
        maven("https://jfrog.anythinktech.com/artifactory/overseas_sdk")

    }
}

rootProject.name = "MySave"
include(":app")
include(":screen:accounts")
include(":screen:mulaBalanc")
include(":screen:budgets")
include(":screen:categories")
include(":screen:disclaimer")
include(":screen:edit-transaction")
include(":screen:exchange-rates")
include(":screen:features")
include(":screen:home")
include(":screen:import-data")
include(":screen:loans")
include(":screen:main")
include(":screen:onboarding")
include(":screen:piechart")
include(":screen:iliyopangwaPayments")
include(":screen:reportStatements")
include(":screen:seek")
include(":screen:controls")
include(":screen:transfers")
include(":common:base")
include(":common:common-userInterface")
include(":common:data:core")
include(":common:data:core-testing")
include(":common:data:model")
include(":common:data:model-testing")
include(":common:domain")
include(":common:userInterface:core")
include(":common:userInterface:navigation")
include(":common:userInterface:testing")
include(":temp:legacy-code")
include(":temp:old-design")
include(":widget:add-transaction")
include(":widget:mulaBalanc")
include(":widget:common-base")
include(":screen:attributions")
